[project]
name = "airflow-dev"
version = "0.1.0"
description = "Development environment for Apache Airflow"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow[celery]==3.0.3",
    "apache-airflow-providers-fab",
    "pandas==2.2.3",
    "graphviz==0.21",
]
